<?php
/**
 * @category    M2Commerce Enterprise
 * @package     M2Commerce_ProductAttachments
 * @copyright   Copyright (c) 2023 M2Commerce Enterprise
 * @author      dawoodgondaldev@gmail.com
 */

/** @var \M2Commerce\ProductAttachments\Block\Product\View\Attachment $block */

$attachments = $block->getAttachments();
if (empty($attachments)) {
    return;
} ?>
<ul class="m2c-product-attachments">
    <?php foreach ($attachments as $attachment): ?>
        <li>
            <a href="<?= $block->escapeHtml($attachment['link']) ?>" target="_blank" title="<?= $block->escapeHtml($attachment['label']) ?>">
                <?= $block->escapeHtml(__($attachment['label'])) ?>
            </a>
        </li>
    <?php endforeach; ?>
</ul>
